version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: apaw_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: assistente_escopo
      MYSQL_USER: apaw_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: apaw_backend_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://apaw_user:${MYSQL_PASSWORD}@db:3306/assistente_escopo
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: apaw_frontend_web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data: