version: '3.8'

services:
  db:      
    image: mysql:8.0
    container_name: assistente_escopo_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: assistente_escopo
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./backend/database:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - rede_projeto

  backend:
    build: ./backend
    container_name: apaw_backend_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://apaw_user:${MYSQL_PASSWORD}@db:3306/assistente_escopo
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: apaw_frontend_web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:

networks:
  rede_projeto:
    driver: bridge
